#!/usr/bin/expect -f

set timeout 60
set password [lindex $argv 0];

# ---> Commands go here !!!!!
#set command "yum remove htop"

catch {spawn -noecho ./myscript.sh {*}$argv}
expect "Password:" {
        send "$password\r"
}

# Get the commands to run, one per line
set f [open "commands.txt"]
set commands [split [read $f] "\n"]
close $f
# Iterate over the commands
foreach cmd $commands {
  expect "*]#\ " {send "$cmd\r"}
}
expect "*]#\ " {send "exit\r"}
expect eof
